version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  graphdb:
    image: khaller/graphdb-free:10.0.0
    container_name: graphdb
    ports:
      - 7200:7200
    environment:
      - JVM_OPTS=-Xmx4g
      - GRAPHDB_HOME=/opt/graphdb/home
    volumes:
      - ./graphdb-data:/opt/graphdb/home

